# Generated by Django 5.2.6 on 2025-10-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_doc_cliente', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], max_length=3)),
                ('doc_cliente', models.CharField(max_length=11, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_cliente', models.CharField(choices=[('frecuente', 'Frecuente'), ('casual', 'Casual')], max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maquina',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('referencia_id', models.BigIntegerField(blank=True, null=True)),
                ('referencia_tabla', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True)),
                ('creado_por_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sede',
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id_notif_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.BigIntegerField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_notificados', to='metal_ops.notificacion')),
            ],
            options={
                'db_table': 'notificacion_usuario',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id_ot', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_ot', models.CharField(choices=[('EN_COLA', 'En cola'), ('URGENTE', 'Urgente'), ('CORRECCION', 'Corrección')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('estado_ot', models.CharField(default='PENDIENTE', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='metal_ops.cliente')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='metal_ops.sede')),
            ],
            options={
                'db_table': 'orden_trabajo',
            },
        ),
        migrations.CreateModel(
            name='FlujoTarea',
            fields=[
                ('id_flujo_tarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden_ejecucion', models.PositiveIntegerField()),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos', to='metal_ops.ordentrabajo')),
            ],
            options={
                'db_table': 'flujo_tarea',
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id_archivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='ordenes_adjuntos/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='metal_ops.ordentrabajo')),
            ],
            options={
                'db_table': 'archivo_adjunto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina', to='metal_ops.maquina')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_tarea', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('EN_CORRECCION', 'En corrección')], max_length=20)),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('tiempo_planificado', models.DurationField(blank=True, null=True)),
                ('tiempo_real', models.DurationField(blank=True, null=True)),
                ('flujo_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='metal_ops.flujotarea')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metal_ops.maquina')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal_ops.servicio')),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
    ]
