# Generated by Django 5.2.6 on 2025-10-24 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='referencia_tabla',
            new_name='referencia',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='creado_por_id',
            new_name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='hora_creacion',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='responsables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('MENSAJE', 'Mensaje'), ('ACTUALIZACIÓN', 'Actualización'), ('CORRECCION', 'Corrección')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina', to='metal_ops.maquina'),
        ),
    ]
