# Generated by Django 5.2.6 on 2025-09-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc_cliente', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], max_length=3, verbose_name='Tipo de documento')),
                ('doc_cliente', models.CharField(max_length=11, verbose_name='Documento del cliente')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre completo / Razón social')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('celular_cliente', models.CharField(max_length=15, verbose_name='Celular')),
                ('tipo_cliente', models.CharField(choices=[('Frecuente', 'Frecuente'), ('Casual', 'Casual')], max_length=10, verbose_name='Tipo de cliente')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='', max_length=128),
        ),
    ]
