# Generated by Django 5.2.6 on 2025-11-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
