# Generated by Django 5.2.6 on 2025-11-10 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0002_tarea_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajoServicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_incluidos', to='metal_ops.ordentrabajo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='metal_ops.servicio')),
            ],
            options={
                'db_table': 'orden_trabajo_servicio',
                'unique_together': {('orden_trabajo', 'servicio')},
            },
        ),
    ]
