# Generated by Django 5.2.6 on 2025-11-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0003_ordentrabajoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
