# Generated by Django 5.2.6 on 2025-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0004_ordentrabajo_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='maquina',
            name='usuario_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
