# Generated by Django 5.2.6 on 2025-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0005_maquina_estado_maquina_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
