# Generated by Django 5.2.6 on 2025-11-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_ops', '0006_tarea_fecha_fin_programada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado_tarea',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('EN_CORRECCION', 'En corrección')], default='PENDIENTE', max_length=20),
        ),
    ]
